<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Driver\NearbyDriverRequest;
use App\Models\Driver;
use App\Services\DriverSimulator;
use App\Support\Geo;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Collection;

/**
 * Available cars around the rider, for the home-screen map shown before
 * ordering. Returns positions only (no driver PII).
 *
 * When `babiauto.simulate_drivers` is on, positions are generated by
 * DriverSimulator so the cars appear to move between polls. Otherwise the
 * drivers' last known real positions (within the match radius) are returned.
 */
class NearbyDriverController extends Controller
{
    public function __construct(private DriverSimulator $simulator) {}

    public function index(NearbyDriverRequest $request): JsonResponse
    {
        $data = $request->validated();
        $lat = (float) $data['lat'];
        $lng = (float) $data['lng'];
        $limit = $data['limit'] ?? 25;
        $simulate = (bool) config('babiauto.simulate_drivers');

        $drivers = Driver::query()
            ->available()
            ->with('vehicleClass')
            ->when(! empty($data['vehicle_class']), fn ($q) => $q->whereHas(
                'vehicleClass',
                fn ($c) => $c->where('slug', $data['vehicle_class'])
            ))
            ->get();

        $positions = $simulate
            ? $this->simulator->positionsAround($drivers, $lat, $lng)
            : $this->realPositions($drivers, $lat, $lng);

        $positions = $positions
            ->sortBy('distance_km')
            ->take($limit)
            ->values();

        return response()->json([
            'data' => $positions,
            'meta' => [
                'simulated' => $simulate,
                'count' => $positions->count(),
                'center' => ['lat' => $lat, 'lng' => $lng],
            ],
        ]);
    }

    /**
     * @param  Collection<int, Driver>  $drivers
     * @return Collection<int, array<string, mixed>>
     */
    private function realPositions(Collection $drivers, float $lat, float $lng): Collection
    {
        $radius = (float) config('babiauto.match_radius_km');

        return $drivers
            ->filter(fn (Driver $d) => $d->current_lat !== null && $d->current_lng !== null)
            ->map(fn (Driver $d) => $this->simulator->shape(
                $d,
                $d->current_lat,
                $d->current_lng,
                null,
                Geo::distanceKm($lat, $lng, $d->current_lat, $d->current_lng),
                false,
            ))
            ->filter(fn (array $p) => $p['distance_km'] <= $radius)
            ->values();
    }
}
